#!/usr/bin/env python3
class PIN:
    MOTOR_TRAIN_1_ENABLE = 18
    FORWARD_TRAIN_1_PIN = 17
    BACKWARD_TRAIN_1_PIN = 27
    
    MOTOR_TRAIN_2_ENABLE = 12
    FORWARD_TRAIN_2_PIN = 13
    BACKWARD_TRAIN_2_PIN = 19    